# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: GitVersion@4
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- bash: |
    npm install -g typescript
    tsc -v
    npm install -g mocha mocha-junit-reporter
    mocha -V
  displayName: Install typescript & mocha

- bash: |
    npm install
    tsc
  workingDirectory: src/build-task/AugurkCSharpAnalyzerInstaller
  displayName: Build AugurkCSharpAnalyzerInstaller task

- bash: |
    npm install
    tsc
  workingDirectory: src/build-task/AugurkCSharpAnalyzer
  displayName: Build AugurkCSharpAnalyzer task

- bash: |
    npm install
    tsc
  workingDirectory: src/build-task/AugurkCLIInstaller
  displayName: Build AugurkCLIInstaller task

- bash: |
    npm install
    tsc
    mocha tests/_suite.js --reporter mocha-junit-reporter
  workingDirectory: src/build-task/AugurkCLI
  displayName: Build AugurkCLI task
  env:
    TASK_TEST_TRACE: 1

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/TEST-RESULTS.xml'
    mergeTestResults: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/**/*.js.log'
    artifactName: testlogs

- task: PackageVSTSExtension@1
  displayName: Package extension
  inputs:
    rootFolder: src
    outputPath: $(Build.ArtifactStagingDirectory)/augurk-preview.vsix

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)/augurk-preview.vsix
    artifactName: vsix
