# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: GitVersion@3
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: |
    npm install
    npx tsc -v
    npx tsc
  workingDirectory: src/build-task/AugurkCSharpAnalyzerInstaller
  displayName: Build AugurkCSharpAnalyzerInstaller task

- script: |
    npm install
    npx tsc -v
    npx tsc
  workingDirectory: src/build-task/AugurkCSharpAnalyzer
  displayName: Build AugurkCSharpAnalyzer task

- task: PackageVSTSExtension@1
  displayName: Package extension
  inputs:
    rootFolder: src
    outputPath: $(Build.ArtifactStagingDirectory)/augurk-preview.vsix

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)/augurk-preview.vsix
    artifactName: vsix
